version: 0.2

phases:
  pre_build:
    commands:
      - cd portal && npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: portal/build
